 const Type = {
    pervDataOfTweets: "PERV_DATA_OF_TWEETS",
    addNewTweet: "ADD_NEW_TWEET",
    pervDataOfReplies: "PERV_DATA_OF_REPLIES",
    addNewReply: "ADD_NEW_REPLY",
    logInS: "LOGIN_SUCCESS",
    logInE: "LOGIN_ERROR",
    signUpS: "SIGNUP_SUCCESS",
    signUpE: "SIGNUP_ERROR",
    remove: "REMOVE",
    currentUser: "CURRENT_USER",
    currentUserError: "CURRENT_USER_NULL",
    logOut: "LOGOUT",
    logInVE: "LOGIN_VALIDATION_EMAIL",
    logInVP: "LOGIN_VALIDATION_PASSWORD",
    SignUpVE: "SINGUP_VALIDATION_EMAIL",
    SignUpVP: "SINGUP_VALIDATION_PASSWORD",
    validate: "VALIDATION",
    removeErrorMess: "REMOVE_ERROR_MESSAGES",
    pervDataOfAllUsers: "PERV_DATA_OF_ALL_USERS",
    likedTweet: "LIKED_TWEET",
    pervDataOfLikes: "PERV_DATA_OF_LIKIES",
    deleteTweet: "DELETE_TWEET",
}
export default Type;